package week7;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class gmail {

	public static void main(String[] args) throws AWTException, InterruptedException {
		// TODO Auto-generated method stub
		//launch chrome
		System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
		ChromeDriver driver =new ChromeDriver();
		//navigate to the URL
		driver.get("https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1#identifier");
        //maximise the window
		driver.manage().window().maximize();
		//implicit wait
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		//enter username
		driver.findElementById("Email").sendKeys("indhusan.12");
		//click next button
		driver.findElementById("next").click();
		//enter password
		driver.findElementById("Passwd").sendKeys("lovelylife");
		//uncheck the stay signed in checkbox
	  driver.findElementById("PersistentCookie").click();
	
		//click signin
		driver.findElementById("signIn").click();
		//click compose
		driver.findElementByXPath("//*[@id=':j2']/div/div").click();
		//enter recepiant id
		driver.findElementByXPath("(//input[@class='wA'])[1]/following::textarea").sendKeys("muthukumar.thiagarajan84@gmail.com");
		//enter subject
		driver.findElementByName("subjectbox").sendKeys("Test mail");
		//enter the content of the mail
		driver.findElementByXPath("//div[@class='Am Al editable LW-avf']").sendKeys("This is an autogenerated mail");
		//click on the attachment icon
		driver.findElementByXPath("//div[@class='a1 aaA aMZ']").click();
		//slect the file that you want to upload
		StringSelection stringSelection =new StringSelection("D:\\Core Java Interview Questions.pdf");
		//paste it in clipboard
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
		//Paste it using robot class
		Robot rb=new Robot();
		rb.keyPress(KeyEvent.VK_CONTROL);
		rb.keyPress(KeyEvent.VK_V);
		rb.keyRelease(KeyEvent.VK_V);
		rb.keyRelease(KeyEvent.VK_CONTROL);
		Thread.sleep(5000);
		//Enter to confirm if it is uploaded
		rb.keyPress(KeyEvent.VK_ENTER);
		rb.keyRelease(KeyEvent.VK_ENTER);
		System.out.println("File successfully uploaded");
		Thread.sleep(3000);
		//Click send 
		driver.findElementByXPath("//div[@class='T-I J-J5-Ji aoO T-I-atl L3']").click();
		System.out.println("Your message has been sent successfully");
		
	}

}
